version: '2'

services:
  web:
    image: nginx:1.18.0-alpine
    restart: unless-stopped
    volumes:
      - wp_data:/var/www/html
      - wp_content:/var/www/html/wp-content
      - ./conf/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./conf/nginx/site.conf:/etc/nginx/conf.d/default.conf
    networks:
      - ext
      - fpm
    ports:
      - ${HTTP_PORT}:80
    depends_on:
      - wp
  wp:
    image: wordpress:5.7.0-php7.4-fpm
    restart: unless-stopped
    volumes:
      - wp_data:/var/www/html
      - wp_content:/var/www/html/wp-content
      - ./conf/php/custom.ini:/usr/local/etc/php/conf.d/custom.ini:ro
    networks:
      - fpm
      - db
    depends_on:
      - db
    environment:
      - WORDPRESS_DB_HOST=db:3306
      - WORDPRESS_DB_USER=${DB_WP_USER}
      - WORDPRESS_DB_PASSWORD=${DB_WP_PASS}
      - WORDPRESS_DB_NAME=${DB_WP_DATABASE}
      - WORDPRESS_TABLE_PREFIX=${WP_TABLE_PREFIX}
  db:
    image: mariadb:10.5.9
    restart: unless-stopped
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - db
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=${DB_RANDOM_ROOT_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
      - MYSQL_DATABASE=${DB_WP_DATABASE}
      - MYSQL_USER=${DB_WP_USER}
      - MYSQL_PASSWORD=${DB_WP_PASS}

networks:
  ext:
    driver: bridge
  fpm:
    driver: bridge
    internal: true
  db:
    driver: bridge
    internal: true

volumes:
  db_data:
  wp_data:
  wp_content:
